stages:
  - test
  - build
  - deploy:staging
  - deploy:production

variables:
  NODE_CONTAINER: node:18-alpine
  DOCKER_CONTAINER: docker:24.0.7

test:unit:
  stage: test
  image: ${NODE_CONTAINER}
  before_script:
    - apk add --no-cache make g++ python3
  script:
    - yarn
    - yarn test:unit

test:snyk:
  stage: test
  image: ${NODE_CONTAINER}
  script:
    - npm install -g npm@latest
    - npm install -g snyk
    - snyk auth ${SNYK_TOKEN}
    - snyk test --all-projects
    - snyk code test
  allow_failure: true

build:
  stage: build
  image: ${DOCKER_CONTAINER}
  services:
    - ${DOCKER_CONTAINER}-dind
  before_script:
    - echo ${DOCKER_HUB_TOKEN} | docker login -u agiannellah --password-stdin
  script:
    - docker build 
      -t agiannellah/ah-api:latest 
      -t agiannellah/ah-api:${CI_COMMIT_SHORT_SHA} .
    - docker push agiannellah/ah-api:latest
    - docker push agiannellah/ah-api:${CI_COMMIT_SHORT_SHA}

deploy:staging:
  stage: deploy:staging
  image: alpine:latest
  environment: staging
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )'
    - eval $(ssh-agent -s)
    - echo "$EC2_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $EC2_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh $EC2_USER@$EC2_HOST "
      echo $DOCKER_HUB_TOKEN | docker login -u agiannellah --password-stdin;
      docker pull agiannellah/ah-api:latest;
      docker stop amplify-hope-api;
      echo 'amplify-hope-api container stopped';
      docker rm amplify-hope-api;
      echo 'amplify-hope-api container removed';
      docker run --name amplify-hope-api --env-file ~/.env/.ah-api.env -p 3002:3002 -d agiannellah/ah-api:latest;"

deploy:production:
  stage: deploy:production
  image: alpine:latest
  when: manual
  environment: production
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )'
    - eval $(ssh-agent -s)
    - echo "$EC2_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $EC2_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh $EC2_USER@$EC2_HOST "
      echo $DOCKER_HUB_TOKEN | docker login -u agiannellah --password-stdin;
      docker pull agiannellah/ah-api:latest;
      docker stop amplify-hope-api;
      echo 'amplify-hope-api container stopped';
      docker rm amplify-hope-api;
      echo 'amplify-hope-api container removed';
      docker run --name amplify-hope-api --env-file ~/.env/.ah-api.env -p 3002:3002 -d agiannellah/ah-api:latest;"
