image: node:16-alpine

pipelines:
  default:
    - step:
        name: test
        script:
          - yarn add -D ts-mocha
          - yarn test:unit
    - step: 
        name: build
        script:
          - yarn add -D typescript
          - yarn build
        artifacts:
          - build/**
    - step:
        name: snyk
        script:
          - pipe: snyk/snyk-scan:0.5.3
            variables:
              SNYK_TOKEN: $SNYK_TOKEN
              LANGUAGE: npm
