image: node:16-alpine

pipelines:
  default:
    - step:
        name: test
        script:
          - yarn add -D ts-mocha
          - yarn test:unit
    - step:
        name: build
        script:
          - echo $BITBUCKET_BUILD_NUMBER
          - echo $BITBUCKET_COMMIT
    - step:
        name: snyk
        script:
          - pipe: snyk/snyk-scan:0.5.3
            variables:
              SNYK_TOKEN: $SNYK_TOKEN
              LANGUAGE: npm
  branches:
    develop:
      - step:
          name: deploy-staging
          script:
            - echo "Deploying to stage"
    main:
      - step:
          name: deploy-production
          trigger: manual
          script:
            - echo "Deploying to production"
