image: node:16-alpine

options:
  docker: true

definitions:


pipelines:
  default:
    - step:
        name: test
        script:
          - yarn add -D ts-mocha
          - yarn test:unit
    - step:
        name: build
        script:
          - export BITBUCKET_COMMIT_SHORT_SHA="${BITBUCKET_COMMIT::5}"
          - echo BITBUCKET_COMMIT_SHORT_SHA
    - step:
        name: snyk
        script:
          - pipe: snyk/snyk-scan:0.5.3
            variables:
              SNYK_TOKEN: $SNYK_TOKEN
              LANGUAGE: npm
  branches:
    develop:
      - step:
          name: deploy-staging
          script:
            - echo "Deploying to stage"
    main:
      - step:
          name: deploy-production
          trigger: manual
          script:
            - echo "Deploying to production"
