image: node:16-alpine

options:
  docker: true

definitions:


pipelines:
  default:
    - step:
        name: test
        script:
          - yarn add -D ts-mocha
          - yarn test:unit
    - step:
        name: build and push
        script:
          - export BITBUCKET_COMMIT_SHORT_SHA="${BITBUCKET_COMMIT::7}"
          - docker login -u agiannellah -p $DOCKER_HUB_TOKEN
          - docker build 
            -t amplify-hope-api:latest
            -t amplify-hope-api:$BITBUCKET_COMMIT_SHORT_SHA
          - docker push amplify-hope-api:latest
          - docker push amplify-hope-api:$BITBUCKET_COMMIT_SHORT_SHA
    - step:
        name: snyk
        script:
          - pipe: snyk/snyk-scan:0.5.3
            variables:
              SNYK_TOKEN: $SNYK_TOKEN
              LANGUAGE: npm
  branches:
    develop:
      - step:
          name: deploy-staging
          script:
            - echo "Deploying to stage"
    main:
      - step:
          name: deploy-production
          trigger: manual
          script:
            - echo "Deploying to production"
