version: '3.9'

services:
  db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgres/data
      - ./src/init-db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
